import torch
import torch.nn.functional as F
from PIL import Image
import open_clip

class CLIPFeatureExtractor:
    """Extracts OpenCLIP embeddings and distances to anchor distributions."""
    
    def __init__(self, model_name="ViT-B-32", pretrained="laion2b_s34b_b79k"):
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        print(f"Loading CLIP model {model_name}...")
        self.model, _, self.preprocess = open_clip.create_model_and_transforms(
            model_name, pretrained=pretrained
        )
        self.model.eval().to(self.device)
        
        # Hardcoded anchor prompts for zero-shot text matching as generic features.
        # In a full research setup, these would be averaged image embeddings 
        # from the training dataset for Real, GAN, and Diffusion classes.
        prompts = [
            "a real authentic photograph", 
            "an AI generated deepfake image",
            "a synthetic image generated by stable diffusion",
            "a StyleGAN generated face"
        ]
        tokenizer = open_clip.get_tokenizer(model_name)
        text = tokenizer(prompts).to(self.device)
        
        with torch.no_grad():
            self.text_features = self.model.encode_text(text)
            self.text_features /= self.text_features.norm(dim=-1, keepdim=True)

    def extract(self, pil_img: Image.Image) -> list[float]:
        """Returns similarity scores to standard text prompts as features."""
        image = self.preprocess(pil_img).unsqueeze(0).to(self.device)
        
        with torch.no_grad():
            image_features = self.model.encode_image(image)
            image_features /= image_features.norm(dim=-1, keepdim=True)
            
            # shape: [1, num_prompts]
            similarity = (image_features @ self.text_features.T)
        
        return similarity.squeeze(0).cpu().numpy().tolist()
